version: '2'
services:
  microapp-app:
    image: microapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://microapp-mysql:3306/microapp?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://microapp-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://microapp-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://microapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://microapp-elasticsearch:9200
  microapp-mysql:
    extends:
      file: mysql.yml
      service: microapp-mysql
  microapp-redis:
    extends:
      file: redis.yml
      service: microapp-redis
  microapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: microapp-elasticsearch
